### ISSUE TITLE
[bug] Precedence error between ":=" and "in"

### ISSUE THREAD

**Issue by mbalunovic** [invariantlabs-ai/invariant#10]
Bug in parser due to the precedence error, failing test: https://github.com/invariantlabs-ai/invariant/commit/70d0f39de6f02bebb2e017da52cd20670ca5d85a

**Comment by lbeurerkellner** [comment]
Fixed in https://github.com/invariantlabs-ai/invariant/commit/47e5c1045f650a44bc27bc0573d5f6edef5863fa. I also added some more comments to the parser.py.
